/**
 * This file is part of the CRISTAL-iSE kernel.
 * Copyright (c) 2001-2015 The CRISTAL Consortium. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation; either version 3 of the License, or (at
 * your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; with out even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation,
 * Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
 *
 * http://www.fsf.org/licensing/licenses/lgpl.html
 */
#ifndef __com_CommonExceptions_Idl__
#define __com_CommonExceptions_Idl__

/*
 * Copyright (C) 2001 CERN - European Organization for Nuclear Research
 * All rights reserved.
 *
 * @author $Author: abranson $ $Date: 2004/01/21 16:17:18 $
 * @version $Revision: 1.6 $
 */

#pragma prefix "org.cristalise.kernel"

module common
{
    /**************************************************************************
    * Thrown when the process isn't privileged enough to make the requested 
    * change, either because it is a client process, or its management objects
    * are incorrect.
    **************************************************************************/
    exception CannotManageException
    {
    };



    /**************************************************************************
    * The requested transition is not currently available, or does not exist.
    * Most commonly occurs when the Activity is in a different state than the
    * caller has assumed.
    **************************************************************************/
    exception InvalidTransitionException
    {
    };
    
    /**************************************************************************
    * The modification to the collection could not be performed, due to rules
    * within the collection itself.
    **************************************************************************/
    exception InvalidCollectionModification
    {
    };


    /**************************************************************************
    * Either the supplied data, or the relevant description, was invalid.
    **************************************************************************/
    exception InvalidDataException
    {
    };


    /**************************************************************************
    * The given agent is not permitted to perform the requested action.
    **************************************************************************/
    exception AccessRightsException
    {
    };


    /**************************************************************************
    * The requested object was not found
    **************************************************************************/
    exception ObjectNotFoundException
    {
    };


    /**************************************************************************
    * Error during storing/retrieving objects
    **************************************************************************/
    exception PersistencyException
    {
    };

    /**************************************************************************
    * The object already exists.
    **************************************************************************/
    exception ObjectAlreadyExistsException
    {
    };


    /**************************************************************************
    * The object cannot be changed.
    **************************************************************************/
    exception ObjectCannotBeUpdated
    {
    };

}; //end of module common

#endif
